// Central question data registry
// Auto-generated by scripts/generate-data.js
import type { Question } from '@/types/question';

import { A1_2024 } from '@/data/questions/A1/2024';
import { A1_2023 } from '@/data/questions/A1/2023';
import { A2_2024 } from '@/data/questions/A2/2024';
import { A2_2023 } from '@/data/questions/A2/2023';
import { B1_2024 } from '@/data/questions/B1/2024';
import { B1_2023 } from '@/data/questions/B1/2023';
import { B2_2024 } from '@/data/questions/B2/2024';
import { B2_2023 } from '@/data/questions/B2/2023';
import { C1_2024 } from '@/data/questions/C1/2024';
import { C1_2023 } from '@/data/questions/C1/2023';

// All questions grouped by qualification ID
export const allQuestions: Record<string, Question[]> = {
  A1: [
    ...A1_2024,
    ...A1_2023,
  ],
  A2: [
    ...A2_2024,
    ...A2_2023,
  ],
  B1: [
    ...B1_2024,
    ...B1_2023,
  ],
  B2: [
    ...B2_2024,
    ...B2_2023,
  ],
  C1: [
    ...C1_2024,
    ...C1_2023,
  ],
};

// Question count by qualification and year (for display)
export const questionCounts: Record<string, Record<string, number>> = {};
for (const [qualId, questions] of Object.entries(allQuestions)) {
  questionCounts[qualId] = {};
  for (const q of questions) {
    const year = String(q.year);
    questionCounts[qualId][year] = (questionCounts[qualId][year] || 0) + 1;
  }
}

// Helper to get questions for a specific qualification
export function getQuestions(qualificationId: string): Question[] {
  return allQuestions[qualificationId] || [];
}

// Helper to get question counts for a qualification
export function getQuestionCounts(qualificationId: string): Record<string, number> {
  return questionCounts[qualificationId] || {};
}
