// Central question data registry
// Auto-generated by scripts/generate-data.js
import type { Question } from '@/types/question';

import { A1_2024 } from '@/data/questions/A1/2024';
import { A1_2023 } from '@/data/questions/A1/2023';
import { A1_2022 } from '@/data/questions/A1/2022';
import { A1_2021 } from '@/data/questions/A1/2021';
import { A1_2020 } from '@/data/questions/A1/2020';
import { A1_2019 } from '@/data/questions/A1/2019';
import { A1_2018 } from '@/data/questions/A1/2018';
import { A1_2017 } from '@/data/questions/A1/2017';
import { A1_2016 } from '@/data/questions/A1/2016';
import { A1_2015 } from '@/data/questions/A1/2015';
import { A2_2024 } from '@/data/questions/A2/2024';
import { A2_2023 } from '@/data/questions/A2/2023';
import { A2_2022 } from '@/data/questions/A2/2022';
import { A2_2021 } from '@/data/questions/A2/2021';
import { A2_2020 } from '@/data/questions/A2/2020';
import { A2_2019 } from '@/data/questions/A2/2019';
import { A2_2018 } from '@/data/questions/A2/2018';
import { A2_2017 } from '@/data/questions/A2/2017';
import { A2_2016 } from '@/data/questions/A2/2016';
import { A2_2015 } from '@/data/questions/A2/2015';
import { B1_2024 } from '@/data/questions/B1/2024';
import { B1_2023 } from '@/data/questions/B1/2023';
import { B1_2022 } from '@/data/questions/B1/2022';
import { B1_2021 } from '@/data/questions/B1/2021';
import { B1_2020 } from '@/data/questions/B1/2020';
import { B1_2019 } from '@/data/questions/B1/2019';
import { B1_2018 } from '@/data/questions/B1/2018';
import { B1_2017 } from '@/data/questions/B1/2017';
import { B1_2016 } from '@/data/questions/B1/2016';
import { B1_2015 } from '@/data/questions/B1/2015';
import { B2_2024 } from '@/data/questions/B2/2024';
import { B2_2023 } from '@/data/questions/B2/2023';
import { B2_2022 } from '@/data/questions/B2/2022';
import { B2_2021 } from '@/data/questions/B2/2021';
import { B2_2020 } from '@/data/questions/B2/2020';
import { B2_2019 } from '@/data/questions/B2/2019';
import { B2_2018 } from '@/data/questions/B2/2018';
import { B2_2017 } from '@/data/questions/B2/2017';
import { B2_2016 } from '@/data/questions/B2/2016';
import { B2_2015 } from '@/data/questions/B2/2015';
import { C1_2024 } from '@/data/questions/C1/2024';
import { C1_2023 } from '@/data/questions/C1/2023';
import { C1_2022 } from '@/data/questions/C1/2022';
import { C1_2021 } from '@/data/questions/C1/2021';
import { C1_2020 } from '@/data/questions/C1/2020';
import { C1_2019 } from '@/data/questions/C1/2019';
import { C1_2018 } from '@/data/questions/C1/2018';
import { C1_2017 } from '@/data/questions/C1/2017';
import { C1_2016 } from '@/data/questions/C1/2016';
import { C1_2015 } from '@/data/questions/C1/2015';
import { C2_2024 } from '@/data/questions/C2/2024';
import { C2_2023 } from '@/data/questions/C2/2023';
import { C2_2022 } from '@/data/questions/C2/2022';
import { C2_2021 } from '@/data/questions/C2/2021';
import { C2_2020 } from '@/data/questions/C2/2020';
import { C2_2019 } from '@/data/questions/C2/2019';
import { C2_2018 } from '@/data/questions/C2/2018';
import { C2_2017 } from '@/data/questions/C2/2017';
import { C2_2016 } from '@/data/questions/C2/2016';
import { C2_2015 } from '@/data/questions/C2/2015';
import { C3_2024 } from '@/data/questions/C3/2024';
import { C3_2023 } from '@/data/questions/C3/2023';
import { C3_2022 } from '@/data/questions/C3/2022';
import { C3_2021 } from '@/data/questions/C3/2021';
import { C3_2020 } from '@/data/questions/C3/2020';
import { C3_2019 } from '@/data/questions/C3/2019';
import { C3_2018 } from '@/data/questions/C3/2018';
import { C3_2017 } from '@/data/questions/C3/2017';
import { C3_2016 } from '@/data/questions/C3/2016';
import { C3_2015 } from '@/data/questions/C3/2015';
import { D1_2024 } from '@/data/questions/D1/2024';
import { D1_2023 } from '@/data/questions/D1/2023';
import { D1_2022 } from '@/data/questions/D1/2022';
import { D1_2021 } from '@/data/questions/D1/2021';
import { D1_2020 } from '@/data/questions/D1/2020';
import { D1_2019 } from '@/data/questions/D1/2019';
import { D1_2018 } from '@/data/questions/D1/2018';
import { D1_2017 } from '@/data/questions/D1/2017';
import { D1_2016 } from '@/data/questions/D1/2016';
import { D1_2015 } from '@/data/questions/D1/2015';
import { D2_2024 } from '@/data/questions/D2/2024';
import { D2_2023 } from '@/data/questions/D2/2023';
import { D2_2022 } from '@/data/questions/D2/2022';
import { D2_2021 } from '@/data/questions/D2/2021';
import { D2_2020 } from '@/data/questions/D2/2020';
import { D2_2019 } from '@/data/questions/D2/2019';
import { D2_2018 } from '@/data/questions/D2/2018';
import { D2_2017 } from '@/data/questions/D2/2017';
import { D2_2016 } from '@/data/questions/D2/2016';
import { D2_2015 } from '@/data/questions/D2/2015';
import { D3_2024 } from '@/data/questions/D3/2024';
import { D3_2023 } from '@/data/questions/D3/2023';
import { D3_2022 } from '@/data/questions/D3/2022';
import { D3_2021 } from '@/data/questions/D3/2021';
import { D3_2020 } from '@/data/questions/D3/2020';
import { D3_2019 } from '@/data/questions/D3/2019';
import { D3_2018 } from '@/data/questions/D3/2018';
import { D3_2017 } from '@/data/questions/D3/2017';
import { D3_2016 } from '@/data/questions/D3/2016';
import { D3_2015 } from '@/data/questions/D3/2015';
import { E1_2024 } from '@/data/questions/E1/2024';
import { E1_2023 } from '@/data/questions/E1/2023';
import { E1_2022 } from '@/data/questions/E1/2022';
import { E1_2021 } from '@/data/questions/E1/2021';
import { E1_2020 } from '@/data/questions/E1/2020';
import { E1_2019 } from '@/data/questions/E1/2019';
import { E1_2018 } from '@/data/questions/E1/2018';
import { E1_2017 } from '@/data/questions/E1/2017';
import { E1_2016 } from '@/data/questions/E1/2016';
import { E1_2015 } from '@/data/questions/E1/2015';
import { E2_2024 } from '@/data/questions/E2/2024';
import { E2_2023 } from '@/data/questions/E2/2023';
import { E2_2022 } from '@/data/questions/E2/2022';
import { E2_2021 } from '@/data/questions/E2/2021';
import { E2_2020 } from '@/data/questions/E2/2020';
import { E2_2019 } from '@/data/questions/E2/2019';
import { E2_2018 } from '@/data/questions/E2/2018';
import { E2_2017 } from '@/data/questions/E2/2017';
import { E2_2016 } from '@/data/questions/E2/2016';
import { E2_2015 } from '@/data/questions/E2/2015';
import { F3_2024 } from '@/data/questions/F3/2024';
import { F3_2023 } from '@/data/questions/F3/2023';
import { F3_2022 } from '@/data/questions/F3/2022';
import { F3_2021 } from '@/data/questions/F3/2021';
import { F3_2020 } from '@/data/questions/F3/2020';
import { F3_2019 } from '@/data/questions/F3/2019';
import { F3_2018 } from '@/data/questions/F3/2018';
import { F3_2017 } from '@/data/questions/F3/2017';
import { F3_2016 } from '@/data/questions/F3/2016';
import { F3_2015 } from '@/data/questions/F3/2015';
import { F5_2024 } from '@/data/questions/F5/2024';
import { F5_2023 } from '@/data/questions/F5/2023';
import { F5_2022 } from '@/data/questions/F5/2022';
import { F5_2021 } from '@/data/questions/F5/2021';
import { F5_2020 } from '@/data/questions/F5/2020';
import { F5_2019 } from '@/data/questions/F5/2019';
import { F5_2018 } from '@/data/questions/F5/2018';
import { F5_2017 } from '@/data/questions/F5/2017';
import { F5_2016 } from '@/data/questions/F5/2016';
import { F5_2015 } from '@/data/questions/F5/2015';

// All questions grouped by qualification ID
export const allQuestions: Record<string, Question[]> = {
  A1: [
    ...A1_2024,
    ...A1_2023,
    ...A1_2022,
    ...A1_2021,
    ...A1_2020,
    ...A1_2019,
    ...A1_2018,
    ...A1_2017,
    ...A1_2016,
    ...A1_2015,
  ],
  A2: [
    ...A2_2024,
    ...A2_2023,
    ...A2_2022,
    ...A2_2021,
    ...A2_2020,
    ...A2_2019,
    ...A2_2018,
    ...A2_2017,
    ...A2_2016,
    ...A2_2015,
  ],
  B1: [
    ...B1_2024,
    ...B1_2023,
    ...B1_2022,
    ...B1_2021,
    ...B1_2020,
    ...B1_2019,
    ...B1_2018,
    ...B1_2017,
    ...B1_2016,
    ...B1_2015,
  ],
  B2: [
    ...B2_2024,
    ...B2_2023,
    ...B2_2022,
    ...B2_2021,
    ...B2_2020,
    ...B2_2019,
    ...B2_2018,
    ...B2_2017,
    ...B2_2016,
    ...B2_2015,
  ],
  C1: [
    ...C1_2024,
    ...C1_2023,
    ...C1_2022,
    ...C1_2021,
    ...C1_2020,
    ...C1_2019,
    ...C1_2018,
    ...C1_2017,
    ...C1_2016,
    ...C1_2015,
  ],
  C2: [
    ...C2_2024,
    ...C2_2023,
    ...C2_2022,
    ...C2_2021,
    ...C2_2020,
    ...C2_2019,
    ...C2_2018,
    ...C2_2017,
    ...C2_2016,
    ...C2_2015,
  ],
  C3: [
    ...C3_2024,
    ...C3_2023,
    ...C3_2022,
    ...C3_2021,
    ...C3_2020,
    ...C3_2019,
    ...C3_2018,
    ...C3_2017,
    ...C3_2016,
    ...C3_2015,
  ],
  D1: [
    ...D1_2024,
    ...D1_2023,
    ...D1_2022,
    ...D1_2021,
    ...D1_2020,
    ...D1_2019,
    ...D1_2018,
    ...D1_2017,
    ...D1_2016,
    ...D1_2015,
  ],
  D2: [
    ...D2_2024,
    ...D2_2023,
    ...D2_2022,
    ...D2_2021,
    ...D2_2020,
    ...D2_2019,
    ...D2_2018,
    ...D2_2017,
    ...D2_2016,
    ...D2_2015,
  ],
  D3: [
    ...D3_2024,
    ...D3_2023,
    ...D3_2022,
    ...D3_2021,
    ...D3_2020,
    ...D3_2019,
    ...D3_2018,
    ...D3_2017,
    ...D3_2016,
    ...D3_2015,
  ],
  E1: [
    ...E1_2024,
    ...E1_2023,
    ...E1_2022,
    ...E1_2021,
    ...E1_2020,
    ...E1_2019,
    ...E1_2018,
    ...E1_2017,
    ...E1_2016,
    ...E1_2015,
  ],
  E2: [
    ...E2_2024,
    ...E2_2023,
    ...E2_2022,
    ...E2_2021,
    ...E2_2020,
    ...E2_2019,
    ...E2_2018,
    ...E2_2017,
    ...E2_2016,
    ...E2_2015,
  ],
  F3: [
    ...F3_2024,
    ...F3_2023,
    ...F3_2022,
    ...F3_2021,
    ...F3_2020,
    ...F3_2019,
    ...F3_2018,
    ...F3_2017,
    ...F3_2016,
    ...F3_2015,
  ],
  F5: [
    ...F5_2024,
    ...F5_2023,
    ...F5_2022,
    ...F5_2021,
    ...F5_2020,
    ...F5_2019,
    ...F5_2018,
    ...F5_2017,
    ...F5_2016,
    ...F5_2015,
  ],
};

// Question count by qualification and year (for display)
export const questionCounts: Record<string, Record<string, number>> = {};
for (const [qualId, questions] of Object.entries(allQuestions)) {
  questionCounts[qualId] = {};
  for (const q of questions) {
    const year = String(q.year);
    questionCounts[qualId][year] = (questionCounts[qualId][year] || 0) + 1;
  }
}

// Helper to get questions for a specific qualification
export function getQuestions(qualificationId: string): Question[] {
  return allQuestions[qualificationId] || [];
}

// Helper to get question counts for a qualification
export function getQuestionCounts(qualificationId: string): Record<string, number> {
  return questionCounts[qualificationId] || {};
}
